//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraCuuThuatNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int QuestionId { get; set; }
        public string QContent { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime DateAdd { get; set; }
        public System.DateTime DateModify { get; set; }
        public Nullable<int> Reported { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
