//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraCuuThuatNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchHistory
    {
        public string Keyword { get; set; }
        public bool IsExist { get; set; }
        public int Counter { get; set; }
        public System.DateTime DateModify { get; set; }
    }
}
